### ISSUE TITLE
Finalize linting rules

### ISSUE THREAD

**Issue by joshgillies** [joshgillies/node-matrix-import-xml-linter#1]
- [ ] #2 Detect when single root not provided
- [x] #3 Warn if default root node #1 is used
- [ ] #4 Warn where inline references to assetID's exist

**Comment by joshgillies** [comment]
Added #2 to list

**Comment by joshgillies** [comment]
Added #3 to list

**Comment by joshgillies** [comment]
Added #4 to list
